---
# Buildspec for building docker image.
version: 0.2
env:
  shell: /bin/bash
  variables:
    USE_EPOCH: 0
    DIND_VOL_PATH: /var/lib/docker/volumes/agent-resources_user_volume/_data/srcDownload/src

phases:
  install:
    commands:
      - if [ -z ${AWS_ACCOUNT_ID+x} ]; then AWS_ACCOUNT_ID=$(aws sts get-caller-identity | jq -r .Account); fi
      - if ! [ -z ${VERSION+} ]; then echo "Missing required parameter VERSION" && exit 1; fi

#      - pip install ecs-composex
#      - docker pull public.ecr.aws/compose-x/compose-x

      - REGISTRY_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION:-$AWS_DEFAULT_REGION}.amazonaws.com/
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin ${REGISTRY_URI}
      - if ! [ -z ${CODEBUILD_RESOLVED_SOURCE_VERSION+x} ]; then COMMIT_HASH=${CODEBUILD_RESOLVED_SOURCE_VERSION::7}; fi
      - EPOCH=`date +'%Y%m%d'`
      - SUFFIX=${COMMIT_HASH:=$EPOCH}
      - if [ $USE_EPOCH -eq 1 ]; then SUFFIX=$EPOCH; fi
      - |
          if ! [ -z "${CODEBUILD_WEBHOOK_TRIGGER+x}" ]; then
            echo TRIGGER is $CODEBUILD_WEBHOOK_TRIGGER
            PRE=`echo $CODEBUILD_WEBHOOK_TRIGGER|cut -d '/' -f 1`;
            echo PRE is $PRE
            echo SUFFIX is $SUFFIX
            if [ "${PRE}" == "tag" ]; then SUFFIX=`echo $CODEBUILD_WEBHOOK_TRIGGER|cut -d '/' -f 2`; TAG_RELEASE=1 ; fi
          fi
      - echo SUFFIX ends up being $SUFFIX
      - if [ -z ${ARCH} ]; then ARCH=`uname -m`; fi
      - IMAGE_TAG=${SUFFIX}-${ARCH}
      - echo image TAG is ${IMAGE_TAG}
      - IMAGE_URI=${REGISTRY_URI}${REPOSITORY_NAME}:${IMAGE_TAG}
      - echo Image URI is ${IMAGE_URI}

  build:
    commands:
      - docker build . -t ${IMAGE_URI}
      - docker push ${IMAGE_URI}

    finally:
      - rm -rfv ~/.docker
